# -*- coding: utf-8 -*-
"""fifa_fouls_tackles_analysis.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OQC8B-hGyzJJT7mKDL8nRePeExJ0Kt9

# FIFA World Cup 2026 Fouls and Tackles Analysis

This notebook answers the analytical question:

**Do teams that commit more fouls per match have a significantly different average number of tackles per match than teams that commit fewer fouls?**

The workflow is deliberately simple and beginner-friendly:

**raw data -> cleaning -> final dataset -> analysis**

## 1. Analytical Question

**Research question:** Do teams that commit more fouls per match have a significantly different average number of tackles per match than teams that commit fewer fouls?

**Null hypothesis (H0):** There is no significant difference in average tackles per match between teams with higher and lower foul rates.

**Alternative hypothesis (H1):** There is a significant difference in average tackles per match between teams with higher and lower foul rates.
"""

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

"""## 2. Data Collection

The data was manually collected into an Excel workbook from The Stats Don't Lie (TSDL) / the source notes in the workbook.

Main TSDL page: https://www.thestatsdontlie.com/football/world-cup-2026/

**Important note:** The workbook uses `Tackles_Won_Total`, so this analysis is based on tackles won per match.
"""

from google.colab import files

uploaded = files.upload()

file_name = "FIFA_World_Cup_2026_Fouls_Tackles.xlsx"

"""## 3. Data Wrangling

In this section, the raw Excel data is loaded, checked, cleaned, and changed into a final dataset containing only the variables needed for the research question.
"""

file_name = 'FIFA_World_Cup_2026_Fouls_Tackles.xlsx'
raw_data = pd.read_excel(file_name, sheet_name="Raw_Data")

raw_data.head()

raw_data.columns

fouls = raw_data[["Team", "Games_Played", "Fouls_Total"]]
tackles = raw_data[["Team", "Tackles_Won_Total"]]

tackles = tackles.rename(columns={"Tackles_Won_Total": "Tackles_Total"})

df = fouls.merge(tackles, on="Team", how="inner")

df["Fouls_Per_Match"] = df["Fouls_Total"] / df["Games_Played"]

df["Tackles_Per_Match"] = df["Tackles_Total"] / df["Games_Played"]

df = df[["Team", "Fouls_Per_Match", "Tackles_Per_Match"]]


df.head()

df.info()

df.isnull().sum()

df = df.dropna()


df.isnull().sum()

df.head()

"""## 4. Data Preparation and Sampling

**Population:** The target population is teams in the FIFA World Cup 2026 team-level dataset relevant to the research question.

**Sample:** The sample is the set of teams manually collected in this workbook. In this file there are 48 teams.

**Sampling approach:** This is not a random sample. It is an available dataset of teams collected from the source. If the workbook contains all available teams from the source, then it can be described as analysing the available population from that source. The confidence interval and t-test are still useful for practising inference, but the results should be interpreted in relation to the collected dataset.

The median fouls per match is used as the cutoff because it splits the teams into two similarly sized groups and is less affected by very high or very low foul values than the mean.
"""

median_fouls = df["Fouls_Per_Match"].median()


df["Foul_Group"] = df["Fouls_Per_Match"].apply(lambda x: 1 if x > median_fouls else 0)


median_fouls

df.head()

"""## 5. Descriptive Statistics

The mean shows the average tackles per match. The median shows the middle value. The standard deviation shows how spread out the tackles per match values are within each group.
"""

df[["Fouls_Per_Match", "Tackles_Per_Match"]].describe()

group_stats = df.groupby("Foul_Group")["Tackles_Per_Match"].agg(
    ["count", "mean", "median", "std", "min", "max"]
)

group_stats

high_fouls = df[df["Foul_Group"] == 1]["Tackles_Per_Match"]
low_fouls = df[df["Foul_Group"] == 0]["Tackles_Per_Match"]


high_mean = high_fouls.mean()
low_mean = low_fouls.mean()


print("Higher-foul teams mean tackles per match:", high_mean)
print("Lower-foul teams mean tackles per match:", low_mean)

"""## 6. 95% Confidence Interval

Conceptual formula:

**confidence interval = sample mean +/- t critical value * standard error**

**standard error = sample standard deviation / square root of sample size**

A 95% confidence interval gives a likely range for the true mean tackles per match for each foul group, based on the collected data.
"""

high_n = high_fouls.count()
high_std = high_fouls.std()
high_se = high_std / np.sqrt(high_n)
high_t_critical = stats.t.ppf(0.975, df=high_n - 1)
high_margin_error = high_t_critical * high_se
high_ci_lower = high_mean - high_margin_error
high_ci_upper = high_mean + high_margin_error


low_n = low_fouls.count()
low_std = low_fouls.std()
low_se = low_std / np.sqrt(low_n)
low_t_critical = stats.t.ppf(0.975, df=low_n - 1)
low_margin_error = low_t_critical * low_se
low_ci_lower = low_mean - low_margin_error
low_ci_upper = low_mean + low_margin_error


print("Higher-foul teams:")
print("Mean tackles per match:", high_mean)
print("95% confidence interval:", high_ci_lower, "to", high_ci_upper)

print("\nLower-foul teams:")
print("Mean tackles per match:", low_mean)
print("95% confidence interval:", low_ci_lower, "to", low_ci_upper)

groups = ["Lower-foul teams", "Higher-foul teams"]
means = [low_mean, high_mean]


lower_errors = [
    low_mean - low_ci_lower,
    high_mean - high_ci_lower
]

upper_errors = [
    low_ci_upper - low_mean,
    high_ci_upper - high_mean
]


errors = np.array([lower_errors, upper_errors])

# Create the bar chart
plt.figure(figsize=(8, 5))

plt.bar(
    groups,
    means,
    yerr=errors,
    capsize=6
)


plt.title("Average Tackles per Match by Foul Group")
plt.xlabel("Foul Group")
plt.ylabel("Average Tackles per Match")


for i, mean in enumerate(means):
    plt.text(
        i,
        mean + 0.1,
        f"{mean:.2f}",
        ha="center"
    )

plt.tight_layout()
plt.show()

"""## 7. Two-Sample t-Test

This analysis uses Welch's independent two-sample t-test because it compares the average tackles per match of two separate groups and does not assume equal variances.

**H0:** There is no significant difference in average tackles per match between teams with higher and lower foul rates.

**H1:** There is a significant difference in average tackles per match between teams with higher and lower foul rates.
"""

t_statistic, p_value = stats.ttest_ind(high_fouls, low_fouls, equal_var=False)


alpha = 0.05


print("t-statistic:", t_statistic)
print("p-value:", p_value)

"""## 8. Interpretation

The p-value is compared with alpha = 0.05.

If p < 0.05, reject H0.

If p >= 0.05, fail to reject H0.
"""

if p_value < alpha:
    print("Decision: Reject the null hypothesis.")
    print("Conclusion: There is a statistically significant difference in average tackles per match")
    print("between higher-foul and lower-foul teams at alpha = 0.05.")
else:
    print("Decision: Fail to reject the null hypothesis.")
    print("Conclusion: There is not enough evidence of a statistically significant difference")
    print("in average tackles per match between higher-foul and lower-foul teams at alpha = 0.05.")

"""## 9. Final Conclusion

This final cell prints the conclusion using the values calculated from the dataset.
"""

if high_mean > low_mean:
    print("Higher-foul teams had the higher average tackles per match.")
else:
    print("Lower-foul teams had the higher average tackles per match.")

print("Higher-foul teams mean tackles per match:", round(high_mean, 2))
print("Higher-foul teams 95% CI:", round(high_ci_lower, 2), "to", round(high_ci_upper, 2))
print("Lower-foul teams mean tackles per match:", round(low_mean, 2))
print("Lower-foul teams 95% CI:", round(low_ci_lower, 2), "to", round(low_ci_upper, 2))
print("t-test p-value:", round(p_value, 4))

if p_value < alpha:
    print("Because the p-value is below 0.05, the difference is statistically significant.")
else:
    print("Because the p-value is 0.05 or higher, the difference is not statistically significant.")